#!/usr/bin/env Rscript --vanilla

#
# git revision numver generation
# 
# Simple R-script for genration of sequential git revision numbers.
# Due to gits implementation there is no monotonically increasing 
# revision number, such as 'svnversion' offers in the svn version
# control. Therefore it is constructed based on different git 
# information.
# 
# after the initialization of the project one should add a tag
# such as 'git add dev-1'. This will result in revision numbers of
# the format 1.0-<number_of_commits>
#
# Author: Jakob Bossek <jakob.bossek@tu-dortmund.de> 
#

# first get the 'one line per revision' represenation of
# the revisions and count the lines. Finally remove whitespaces.
git_log = system("git log --oneline", TRUE)
revision_counter = length(git_log)

# now extract assigned tag (should be one of prod or dev) and hash
git_description = system("git describe --tags --long", TRUE)
git_description = strsplit(git_description, "-")[[1]]

# extract relevant data
revision_tag       = git_description[1]
revision_major     = git_description[2]
revision_minor     = git_description[3]
revision_hash_head = git_description[4]

# construct git 'version number'
v = paste(revision_major, ".", revision_minor, "-", revision_counter, sep="")
# print(v)

# replace mandatory 'Version' field in DESCRIPTION file of package
# (the file is based on the 'Debian Control File' format)
description = read.dcf("pkg/DESCRIPTION")
description[,"Version"] = v
write.dcf(description, file="pkg/DESCRIPTION")